services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=steepskynet
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=axum-db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/axum-db
      KC_DB_USERNAME: steepskynet
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db